#version: '3.8'

services:
  # Service 1: PHP Application
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: mon_app_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www  # Synchronisation du code en temps réel (bind mount)
    networks:
      - app-network

  # Service 2: Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: mon_app_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80" # Accessible via localhost:8080
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app # Attend que PHP soit prêt avant de lancer Nginx

  # Service 3: Database
  db:
    image: mysql:8.0
    container_name: mon_app_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mon_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: zikalsino
      MYSQL_USER: zik
    ports:
      - "33061:3306" # Pour accéder à la BDD depuis votre outil local (DBeaver, etc.)
    volumes:
      - dbdata:/var/lib/mysql # Persistance des données
    networks:
      - app-network

# Réseaux
networks:
  app-network:
    driver: bridge

# Volumes nommés (pour la persistance)
volumes:
  dbdata: